name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    steps:
      # 1) Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Setup Node.js (for Vite)
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Install & build your frontend
      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      # 4) Deploy to Azure Static Web Apps
      - name: Deploy to Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_PLANT_0C87B0103 }}  # make sure this secret exists
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # used for PR comments, etc.
          action: "upload"
          # path to your app source and build
          app_location: "frontend"
          api_location: ""             # no Azure Functions here
          output_location: "dist"      # where Vite outputs your build
